"""init schema

Revision ID: 8ddaabdca2bd
Revises: 
Create Date: 2026-05-29 15:23:17.851587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ddaabdca2bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('KPI_ADJUSTMENTS',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('requested_by', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('criteria_name', sa.String(length=255), nullable=False),
    sa.Column('original_score', sa.Float(), nullable=True),
    sa.Column('proposed_score', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['requested_by'], ['USERS.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['USERS.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['USERS.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('KPI_APPEALS',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('criteria_name', sa.String(length=255), nullable=False),
    sa.Column('current_score', sa.Float(), nullable=False),
    sa.Column('proposed_score', sa.Float(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('adjusted_score', sa.Float(), nullable=True),
    sa.Column('responded_by', sa.UUID(), nullable=True),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['responded_by'], ['USERS.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['USERS.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('KPI_CONFIG',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('target_score', sa.Float(), nullable=True),
    sa.Column('cycle_day', sa.Integer(), nullable=True),
    sa.Column('threshold_excellent', sa.Float(), nullable=True),
    sa.Column('threshold_good', sa.Float(), nullable=True),
    sa.Column('threshold_pass', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['org_id'], ['ORGANIZATIONS.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['USERS.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('KPI_CRITERIA',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('dept_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('default_weight', sa.Float(), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=True),
    sa.Column('formula_type', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['USERS.id'], ),
    sa.ForeignKeyConstraint(['dept_id'], ['DEPARTMENTS.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['ORGANIZATIONS.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('KPI_FINALIZE',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('is_finalized', sa.Boolean(), nullable=True),
    sa.Column('finalized_by', sa.UUID(), nullable=True),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unlock_reason', sa.Text(), nullable=True),
    sa.Column('unlocked_by', sa.UUID(), nullable=True),
    sa.Column('unlocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['finalized_by'], ['USERS.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['ORGANIZATIONS.id'], ),
    sa.ForeignKeyConstraint(['unlocked_by'], ['USERS.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('org_id', 'year', 'month', name='uq_kpi_finalize')
    )
    op.create_table('KPI_TARGETS',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('target_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['USERS.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'year', 'month', name='uq_kpi_target')
    )
    op.create_table('NOTIFICATION_PREFERENCES',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('push_enabled', sa.Boolean(), nullable=True),
    sa.Column('types', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['USERS.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('PUSH_SUBSCRIPTIONS',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('endpoint', sa.String(), nullable=False),
    sa.Column('p256dh_key', sa.String(), nullable=False),
    sa.Column('auth_key', sa.String(), nullable=False),
    sa.Column('platform', sa.String(length=20), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['USERS.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint')
    )
    op.create_table('USER_SETTINGS',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['USERS.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('KPI_CRITERIA_HISTORY',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('criteria_id', sa.UUID(), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=False),
    sa.Column('old_weight', sa.Float(), nullable=True),
    sa.Column('new_weight', sa.Float(), nullable=True),
    sa.Column('old_name', sa.String(length=255), nullable=True),
    sa.Column('new_name', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['changed_by'], ['USERS.id'], ),
    sa.ForeignKeyConstraint(['criteria_id'], ['KPI_CRITERIA.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('KPI_SCORES',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('criteria_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('weighted_score', sa.Float(), nullable=True),
    sa.Column('is_finalized', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['criteria_id'], ['KPI_CRITERIA.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['USERS.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'criteria_id', 'year', 'month', name='uq_kpi_score')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('KPI_SCORES')
    op.drop_table('KPI_CRITERIA_HISTORY')
    op.drop_table('USER_SETTINGS')
    op.drop_table('PUSH_SUBSCRIPTIONS')
    op.drop_table('NOTIFICATION_PREFERENCES')
    op.drop_table('KPI_TARGETS')
    op.drop_table('KPI_FINALIZE')
    op.drop_table('KPI_CRITERIA')
    op.drop_table('KPI_CONFIG')
    op.drop_table('KPI_APPEALS')
    op.drop_table('KPI_ADJUSTMENTS')
    # ### end Alembic commands ###
